name: Terraform Azure VM for RAN-Connect PoC

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Deploy'
        type: environment
        required: true

env:
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  LOCATION: ${{ vars.LOCATION }}
  CIDR_BLOCK: ${{ vars.CIDR_BLOCK }}

jobs:

  check-env:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Echo environment variables
        run: |
          echo "ARM_TENANT_ID: $ARM_TENANT_ID"
          echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
          echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
          echo "ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET"
          echo "LOCATION: $LOCATION"
          echo "CIDR_BLOCK: $CIDR_BLOCK"
      - name: Az CLI login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"$ARM_CLIENT_ID","clientSecret":"$ARM_CLIENT_SECRET","subscriptionId":"$ARM_SUBSCRIPTION_ID","tenantId":"$ARM_TENANT_ID"}'
      - name: azure account list
        run: az account list

  # checkout-code:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  # terraform-init:
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Terraform Init
  #       run: terraform init
