name: Terraform Azure VM for RAN-Connect PoC

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Deploy'
        type: environment
        required: true

jobs:

  startup:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      ENV_NAME: ${{ github.event.inputs.environment }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      LOCATION: ${{ vars.LOCATION }}
      CIDR_BLOCK: ${{ vars.CIDR_BLOCK }}
    steps:
      - name: Echo environment variables
        run: |
          echo "ENV_NAME: $ENV_NAME"
          echo "ARM_TENANT_ID: $ARM_TENANT_ID"
          echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
          echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
          echo "ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET"
          echo "LOCATION: $LOCATION"
          echo "CIDR_BLOCK: $CIDR_BLOCK"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Az CLI login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: terraform plan
        run: |
          # pwd
          # ls -la
          export COMPONENT=init
          # echo "COMPONENT: $COMPONENT"
          # echo "ENV_NAME: ${ENV_NAME}"
          echo $ARM_CLIENT_SECRET
          cd azure
          source ./env.sh
          cd $COMPONENT
          az account show --output table
          terraform init
          echo "------"
          export TF_LOG=TRACE

          terraform plan


  # terraform-init:
  #   runs-on: ubuntu-latest
  #   needs: check-env
  #   environment: ${{ github.event.inputs.environment }}
  #   env:
  #     ENV_NAME: ${{ github.event.inputs.environment }}
  #     ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  #     ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  #     ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  #     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  #     LOCATION: ${{ vars.LOCATION }}
  #     CIDR_BLOCK: ${{ vars.CIDR_BLOCK }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Az CLI login
  #       uses: Azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Terraform Init
  #       run: |
  #         az account show --output table
  #         cd azure
  #         terraform plan
  #         # ./terraform_runner.sh azure init plan

